<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ContainerResource" tests="2" time="30.929">
  <testsuite name="Upload $dotPageContent_test bundle" id="8ab03cd3-15a4-4eb7-bd02-321ec7b72f0c" timestamp="2023-07-21T17:37:16.815Z" tests="1" failures="0" errors="0" time="27.327">
    <testcase name="Bundle uploaded sucessfully" time="27.327" classname="ContainerResource"/>
  </testsuite>
  <testsuite name="Get Contentlet in Container" id="7e26eb32-d3e1-4482-a243-2cd5d4142031" timestamp="2023-07-21T17:37:16.815Z" tests="1" failures="1" errors="0" time="3.602">
    <testcase name="Render contentlet in container" time="3.602" classname="ContainerResource">
      <failure type="AssertionFailure" message="expected '' to include 'dotPageContent object has the expected values'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 4c97f297-9004-4421-af9f-96b430ebafe6.]]>
        <![CDATA[Collection name: ContainerResource.]]>
        <![CDATA[Request name: Get Contentlet in Container.]]>
        <![CDATA[Test description: Render contentlet in container.]]>
        <![CDATA[Error message: expected '' to include 'dotPageContent object has the expected values'.]]>
        <![CDATA[Stacktrace: AssertionError: expected '' to include 'dotPageContent object has the expected values'
   at Object.eval sandbox-script.js:1:2).]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>