<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="ContainerResource" tests="2" time="38.265">
  <testsuite name="Upload $dotPageContent_test bundle" id="083b6164-f10e-4a5d-b4c4-8cf86d1e171c" timestamp="2023-07-21T17:37:10.463Z" tests="1" failures="0" errors="0" time="34.538">
    <testcase name="Bundle uploaded sucessfully" time="34.538" classname="ContainerResource"/>
  </testsuite>
  <testsuite name="Get Contentlet in Container" id="195a12e9-fd4d-4dc1-9eaa-9bc6f456096b" timestamp="2023-07-21T17:37:10.463Z" tests="1" failures="1" errors="0" time="3.727">
    <testcase name="Render contentlet in container" time="3.727" classname="ContainerResource">
      <failure type="AssertionFailure" message="expected '' to include 'dotPageContent object has the expected values'">
        <![CDATA[Failed 1 times.]]>
        <![CDATA[Collection JSON ID: 4c97f297-9004-4421-af9f-96b430ebafe6.]]>
        <![CDATA[Collection name: ContainerResource.]]>
        <![CDATA[Request name: Get Contentlet in Container.]]>
        <![CDATA[Test description: Render contentlet in container.]]>
        <![CDATA[Error message: expected '' to include 'dotPageContent object has the expected values'.]]>
        <![CDATA[Stacktrace: AssertionError: expected '' to include 'dotPageContent object has the expected values'
   at Object.eval sandbox-script.js:1:2).]]>
      </failure>
    </testcase>
  </testsuite>
</testsuites>